[project]
name = "CLIzip"
#엘렐레
version = "beta 1.1.0"
description = "A simple CLI tool for ZIP&7Z compression/decompression with progress display"
license = { text = "MIT" }
requires-python = "<=3.1.1"
dependencies = [
    "py7zr"
]

[project.scripts]
cps = "cps:main"
decps = "cps:main"
